server:
  host: 0.0.0.0
  port: 8080

database:
  path: hubterm.db

auth:
  jwt_secret: ""
  admin_password: ""

log:
  level: info
  format: json

presets:
  dir: presets

https:
  enabled: true
  port: 8087
  server_name: "3.3.3.3"
  cert_dns: "localhost"
  cert_ip: "3.3.3.3"